// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/delivery/grpc/proto/todo.proto

package proto // import "go-design-pattern-demo/pkg/delivery/grpc/proto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TodoItem struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	UserID               string   `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsChecked            bool     `protobuf:"varint,4,opt,name=IsChecked,proto3" json:"IsChecked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TodoItem) Reset()         { *m = TodoItem{} }
func (m *TodoItem) String() string { return proto.CompactTextString(m) }
func (*TodoItem) ProtoMessage()    {}
func (*TodoItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{0}
}
func (m *TodoItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TodoItem.Unmarshal(m, b)
}
func (m *TodoItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TodoItem.Marshal(b, m, deterministic)
}
func (dst *TodoItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TodoItem.Merge(dst, src)
}
func (m *TodoItem) XXX_Size() int {
	return xxx_messageInfo_TodoItem.Size(m)
}
func (m *TodoItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TodoItem.DiscardUnknown(m)
}

var xxx_messageInfo_TodoItem proto.InternalMessageInfo

func (m *TodoItem) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *TodoItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TodoItem) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *TodoItem) GetIsChecked() bool {
	if m != nil {
		return m.IsChecked
	}
	return false
}

type CheckTodoInput struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckTodoInput) Reset()         { *m = CheckTodoInput{} }
func (m *CheckTodoInput) String() string { return proto.CompactTextString(m) }
func (*CheckTodoInput) ProtoMessage()    {}
func (*CheckTodoInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{1}
}
func (m *CheckTodoInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTodoInput.Unmarshal(m, b)
}
func (m *CheckTodoInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTodoInput.Marshal(b, m, deterministic)
}
func (dst *CheckTodoInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTodoInput.Merge(dst, src)
}
func (m *CheckTodoInput) XXX_Size() int {
	return xxx_messageInfo_CheckTodoInput.Size(m)
}
func (m *CheckTodoInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTodoInput.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTodoInput proto.InternalMessageInfo

func (m *CheckTodoInput) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type CheckTodoOutput struct {
	Result               *TodoItem `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CheckTodoOutput) Reset()         { *m = CheckTodoOutput{} }
func (m *CheckTodoOutput) String() string { return proto.CompactTextString(m) }
func (*CheckTodoOutput) ProtoMessage()    {}
func (*CheckTodoOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{2}
}
func (m *CheckTodoOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTodoOutput.Unmarshal(m, b)
}
func (m *CheckTodoOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTodoOutput.Marshal(b, m, deterministic)
}
func (dst *CheckTodoOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTodoOutput.Merge(dst, src)
}
func (m *CheckTodoOutput) XXX_Size() int {
	return xxx_messageInfo_CheckTodoOutput.Size(m)
}
func (m *CheckTodoOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTodoOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTodoOutput proto.InternalMessageInfo

func (m *CheckTodoOutput) GetResult() *TodoItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type CreateTodoInput struct {
	Description          string   `protobuf:"bytes,1,opt,name=Description,proto3" json:"Description,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoInput) Reset()         { *m = CreateTodoInput{} }
func (m *CreateTodoInput) String() string { return proto.CompactTextString(m) }
func (*CreateTodoInput) ProtoMessage()    {}
func (*CreateTodoInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{3}
}
func (m *CreateTodoInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoInput.Unmarshal(m, b)
}
func (m *CreateTodoInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoInput.Marshal(b, m, deterministic)
}
func (dst *CreateTodoInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoInput.Merge(dst, src)
}
func (m *CreateTodoInput) XXX_Size() int {
	return xxx_messageInfo_CreateTodoInput.Size(m)
}
func (m *CreateTodoInput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoInput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoInput proto.InternalMessageInfo

func (m *CreateTodoInput) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateTodoInput) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CreateTodoOutput struct {
	Result               *TodoItem `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateTodoOutput) Reset()         { *m = CreateTodoOutput{} }
func (m *CreateTodoOutput) String() string { return proto.CompactTextString(m) }
func (*CreateTodoOutput) ProtoMessage()    {}
func (*CreateTodoOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{4}
}
func (m *CreateTodoOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoOutput.Unmarshal(m, b)
}
func (m *CreateTodoOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoOutput.Marshal(b, m, deterministic)
}
func (dst *CreateTodoOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoOutput.Merge(dst, src)
}
func (m *CreateTodoOutput) XXX_Size() int {
	return xxx_messageInfo_CreateTodoOutput.Size(m)
}
func (m *CreateTodoOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoOutput.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoOutput proto.InternalMessageInfo

func (m *CreateTodoOutput) GetResult() *TodoItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type GetTodosInput struct {
	UserID               string   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodosInput) Reset()         { *m = GetTodosInput{} }
func (m *GetTodosInput) String() string { return proto.CompactTextString(m) }
func (*GetTodosInput) ProtoMessage()    {}
func (*GetTodosInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{5}
}
func (m *GetTodosInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosInput.Unmarshal(m, b)
}
func (m *GetTodosInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosInput.Marshal(b, m, deterministic)
}
func (dst *GetTodosInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosInput.Merge(dst, src)
}
func (m *GetTodosInput) XXX_Size() int {
	return xxx_messageInfo_GetTodosInput.Size(m)
}
func (m *GetTodosInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosInput proto.InternalMessageInfo

func (m *GetTodosInput) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetTodosOutput struct {
	Result               []*TodoItem `protobuf:"bytes,1,rep,name=Result,proto3" json:"Result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTodosOutput) Reset()         { *m = GetTodosOutput{} }
func (m *GetTodosOutput) String() string { return proto.CompactTextString(m) }
func (*GetTodosOutput) ProtoMessage()    {}
func (*GetTodosOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_todo_b9fc1f06c96dc529, []int{6}
}
func (m *GetTodosOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodosOutput.Unmarshal(m, b)
}
func (m *GetTodosOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodosOutput.Marshal(b, m, deterministic)
}
func (dst *GetTodosOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodosOutput.Merge(dst, src)
}
func (m *GetTodosOutput) XXX_Size() int {
	return xxx_messageInfo_GetTodosOutput.Size(m)
}
func (m *GetTodosOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodosOutput.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodosOutput proto.InternalMessageInfo

func (m *GetTodosOutput) GetResult() []*TodoItem {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*TodoItem)(nil), "agent.TodoItem")
	proto.RegisterType((*CheckTodoInput)(nil), "agent.CheckTodoInput")
	proto.RegisterType((*CheckTodoOutput)(nil), "agent.CheckTodoOutput")
	proto.RegisterType((*CreateTodoInput)(nil), "agent.CreateTodoInput")
	proto.RegisterType((*CreateTodoOutput)(nil), "agent.CreateTodoOutput")
	proto.RegisterType((*GetTodosInput)(nil), "agent.GetTodosInput")
	proto.RegisterType((*GetTodosOutput)(nil), "agent.GetTodosOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TodoClient is the client API for Todo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TodoClient interface {
	GetTodos(ctx context.Context, in *GetTodosInput, opts ...grpc.CallOption) (*GetTodosOutput, error)
	CreateTodo(ctx context.Context, in *CreateTodoInput, opts ...grpc.CallOption) (*CreateTodoOutput, error)
	CheckTodo(ctx context.Context, in *CheckTodoInput, opts ...grpc.CallOption) (*CheckTodoOutput, error)
}

type todoClient struct {
	cc *grpc.ClientConn
}

func NewTodoClient(cc *grpc.ClientConn) TodoClient {
	return &todoClient{cc}
}

func (c *todoClient) GetTodos(ctx context.Context, in *GetTodosInput, opts ...grpc.CallOption) (*GetTodosOutput, error) {
	out := new(GetTodosOutput)
	err := c.cc.Invoke(ctx, "/agent.Todo/GetTodos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) CreateTodo(ctx context.Context, in *CreateTodoInput, opts ...grpc.CallOption) (*CreateTodoOutput, error) {
	out := new(CreateTodoOutput)
	err := c.cc.Invoke(ctx, "/agent.Todo/CreateTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoClient) CheckTodo(ctx context.Context, in *CheckTodoInput, opts ...grpc.CallOption) (*CheckTodoOutput, error) {
	out := new(CheckTodoOutput)
	err := c.cc.Invoke(ctx, "/agent.Todo/CheckTodo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoServer is the server API for Todo service.
type TodoServer interface {
	GetTodos(context.Context, *GetTodosInput) (*GetTodosOutput, error)
	CreateTodo(context.Context, *CreateTodoInput) (*CreateTodoOutput, error)
	CheckTodo(context.Context, *CheckTodoInput) (*CheckTodoOutput, error)
}

func RegisterTodoServer(s *grpc.Server, srv TodoServer) {
	s.RegisterService(&_Todo_serviceDesc, srv)
}

func _Todo_GetTodos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTodosInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).GetTodos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Todo/GetTodos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).GetTodos(ctx, req.(*GetTodosInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_CreateTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTodoInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).CreateTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Todo/CreateTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).CreateTodo(ctx, req.(*CreateTodoInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Todo_CheckTodo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckTodoInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TodoServer).CheckTodo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.Todo/CheckTodo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TodoServer).CheckTodo(ctx, req.(*CheckTodoInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Todo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Todo",
	HandlerType: (*TodoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTodos",
			Handler:    _Todo_GetTodos_Handler,
		},
		{
			MethodName: "CreateTodo",
			Handler:    _Todo_CreateTodo_Handler,
		},
		{
			MethodName: "CheckTodo",
			Handler:    _Todo_CheckTodo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/delivery/grpc/proto/todo.proto",
}

func init() {
	proto.RegisterFile("pkg/delivery/grpc/proto/todo.proto", fileDescriptor_todo_b9fc1f06c96dc529)
}

var fileDescriptor_todo_b9fc1f06c96dc529 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xd3, 0x82, 0x04, 0x86, 0x08, 0x66, 0xa3, 0xd8, 0x10, 0x0f, 0x4d, 0x2f, 0x70, 0xa1,
	0x35, 0x78, 0x30, 0x62, 0xbc, 0x48, 0x13, 0xd3, 0x78, 0x30, 0x69, 0xf4, 0xe2, 0x0d, 0xe9, 0xa4,
	0x36, 0x40, 0xb7, 0xd9, 0x1d, 0x4c, 0xfc, 0x6b, 0xfe, 0x3a, 0xc3, 0xb2, 0xa5, 0xb4, 0x2a, 0x89,
	0xa7, 0x6e, 0xdf, 0xbc, 0x9d, 0x6f, 0x5e, 0xa7, 0xe0, 0x64, 0x8b, 0xd8, 0x8b, 0x70, 0x99, 0x7c,
	0xa0, 0xf8, 0xf4, 0x62, 0x91, 0xcd, 0xbd, 0x4c, 0x70, 0xe2, 0x1e, 0xf1, 0x88, 0xbb, 0xea, 0xc8,
	0x8e, 0x66, 0x31, 0xa6, 0xe4, 0x08, 0x68, 0x3e, 0xf3, 0x88, 0x07, 0x84, 0x2b, 0xd6, 0x01, 0x33,
	0xf0, 0x2d, 0xc3, 0x36, 0x86, 0xad, 0xd0, 0x0c, 0x7c, 0x66, 0x43, 0xdb, 0x47, 0x39, 0x17, 0x49,
	0x46, 0x09, 0x4f, 0x2d, 0x53, 0x15, 0xf6, 0x25, 0xd6, 0x83, 0xc6, 0x8b, 0x44, 0x11, 0xf8, 0x56,
	0x4d, 0x15, 0xf5, 0x1b, 0xbb, 0x80, 0x56, 0x20, 0xa7, 0xef, 0x38, 0x5f, 0x60, 0x64, 0xd5, 0x6d,
	0x63, 0xd8, 0x0c, 0x0b, 0xc1, 0xb1, 0xa1, 0xa3, 0x8e, 0x0a, 0x9c, 0x66, 0x6b, 0xaa, 0x92, 0x9d,
	0x09, 0x74, 0x77, 0x8e, 0xa7, 0x35, 0x6d, 0x2c, 0x03, 0x68, 0x84, 0x28, 0xd7, 0x4b, 0x52, 0xb6,
	0xf6, 0xb8, 0xeb, 0xaa, 0x00, 0x6e, 0x3e, 0x7d, 0xa8, 0xcb, 0xce, 0x23, 0x74, 0xa7, 0x02, 0x67,
	0x84, 0x45, 0xfb, 0x4a, 0x10, 0xe3, 0x50, 0x10, 0x73, 0x3f, 0x88, 0x73, 0x0b, 0x27, 0x45, 0xb3,
	0xff, 0x4e, 0x32, 0x80, 0xe3, 0x07, 0xa4, 0x8d, 0x2c, 0xb7, 0x73, 0x14, 0x14, 0xa3, 0x44, 0xb9,
	0x81, 0x4e, 0x6e, 0xfc, 0x85, 0x51, 0x3b, 0xc0, 0x18, 0x7f, 0x19, 0x50, 0xdf, 0x88, 0xec, 0x1a,
	0x9a, 0x79, 0x0f, 0x76, 0xaa, 0xdd, 0x25, 0x7a, 0xff, 0xac, 0xa2, 0x6a, 0xd4, 0x1d, 0x40, 0x11,
	0x91, 0xf5, 0xb4, 0xa9, 0xf2, 0x09, 0xfb, 0xe7, 0x3f, 0x74, 0x7d, 0x7d, 0x02, 0xad, 0xdd, 0xaa,
	0x58, 0x8e, 0x28, 0xaf, 0xb7, 0xdf, 0xab, 0xca, 0xdb, 0xbb, 0xf7, 0x97, 0xaf, 0x6e, 0xcc, 0x47,
	0x11, 0xca, 0x24, 0x4e, 0x47, 0xd9, 0x8c, 0x08, 0x45, 0x3a, 0x8a, 0x70, 0xc5, 0xbd, 0x3f, 0x7e,
	0xe0, 0xb7, 0x86, 0x7a, 0x5c, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xab, 0x9a, 0xa0, 0xe2,
	0x02, 0x00, 0x00,
}
